name: Validate JSON

on: [push]

jobs:
  validate-whitelist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Vaulst List
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./vaultsList.schema.json
          INPUT_JSONS: ./vaultsList.json
      - name: Validate Tokens List
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./tokensList.schema.json
          INPUT_JSONS: ./tokensList.json
